name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            🎉 Thank you for your first contribution to Cinephile Corner!
            We're excited to have you here. Please follow the contribution guidelines in the README.
